import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-custom-background-2 custom-sm-ex:bg-custom-background bg-cover bg-no-repeat overflow-x-hidden overflow-y-auto !m-0 !p-0">
        {children}
      </body>
    </html>
  );
}
