
export const techIcons = [
    { iconImage: "/icons/language-icons/html5-svgrepo-com.svg", alt: "html5_icon", title: "HTML5", trueFalse: "html_TF" },
    { iconImage: "/icons/language-icons/css3-svgrepo-com.svg", alt: "css3_icon", title: "CSS3", trueFalse: "css_TF" },
    { iconImage: "/icons/language-icons/javascript-svgrepo-com.svg", alt: "javascript_icon", title: "JavaScript", trueFalse: "javascript_TF" },
    { iconImage: "/icons/language-icons/scss2-svgrepo-com.svg", alt: "sass_icon", title: "SASS/SCSS", trueFalse: "sass_TF" },
    { iconImage: "/icons/language-icons/Astro.svg", alt: "astro_icon", title: "Astro", trueFalse: "astro_TF" },
    { iconImage: "/icons/language-icons/react-1-logo-svgrepo-com.svg", alt: "react_icon", title: "React", trueFalse: "react_TF" },
    { iconImage: "/icons/language-icons/tailwind-svgrepo-com.svg", alt: "tailwind_icon", title: "Tailwind CSS", trueFalse: "tailwindcss_TF" },
    { iconImage: "/icons/language-icons/bootstrap-fill-svgrepo-com.svg", alt: "bootstrap_icon", title: "Bootstrap", trueFalse: "bootstrap_TF" },
    { iconImage: "/icons/language-icons/json-official-svgrepo-com.svg", alt: "json_icon", title: "JSON", trueFalse: "json_TF" },
    { iconImage: "/icons/language-icons/api-svgrepo-com.svg", alt: "api_icon", title: "API", trueFalse: "api_TF" },
    { iconImage: "/icons/other-icons/wouter-github-logo.svg", alt: "wouter_icon", title: "Wouter", trueFalse: "wouter_TF" },
    { iconImage: "/icons/language-icons/nextjs-fill-svgrepo-com.svg", alt: "nextjs_icon", title: "NextJS", trueFalse: "nextjs_TF" },
    { iconImage: "/icons/language-icons/typescript-icon-svgrepo-com.svg", alt: "typescript_icon", title: "TypeScript", trueFalse: "typescript_TF" },
    { iconImage: "/icons/language-icons/redux-svgrepo-com.svg", alt: "redux_icon", title: "Redux", trueFalse: "redux_TF" },
    { iconImage: "/icons/language-icons/postgresql-svgrepo-com.svg", alt: "postgresql_icon", title: "PostgreSQL", trueFalse: "postgresql_TF" },
    { iconImage: "/icons/language-icons/vue-svgrepo-com.svg", alt: "vue_icon", title: "Vue", trueFalse: "vue_TF" },
    { iconImage: "/icons/other-icons/figma-svgrepo-com.svg", alt: "figma_icon", title: "Figma", trueFalse: "figma_TF" },
];

export const techExp = [
    { name: "HTML5", experience: "8+", projectCount: ""},
    { name: "CSS3", experience: "7+", projectCount: ""},
    { name: "JavaScript", experience: "6+", projectCount: ""},
    { name: "SASS/SCSS", experience: "3+", projectCount: ""},
    { name: "Astro", experience: "<1", projectCount: ""},
    { name: "React", experience: "3+", projectCount: ""},
    { name: "Tailwind CSS", experience: "2+", projectCount: ""},
    { name: "Bootstrap", experience: "1+", projectCount: ""},
    { name: "JSON", experience: "3+", projectCount: ""},
    { name: "API", experience: "3+", projectCount: ""},
    { name: "Wouter", experience: "2+", projectCount: ""},
    { name: "NextJS", experience: "<1", projectCount: ""},
    { name: "TypeScript", experience: "1+", projectCount: ""},
    { name: "Redux", experience: "1+", projectCount: ""},
    { name: "PostgreSQL", experience: "1+", projectCount: ""},
    { name: "Vue", experience: "<1", projectCount: ""},
    { name: "Figma", experience: "2+", projectCount: ""}
];