export const externalLinks = [
    { name: "GitHub", userID: "Zy8712", link: "https://github.com/Zy8712", icon: "/icons/social-icons/coloured-icons/github-142-svgrepo-com.svg", },
    { name: "LinkedIn", userID: "bryan-li712", link: "https://www.linkedin.com/in/bryan-li712/", icon: "/icons/social-icons/coloured-icons/linkedin-icon-svgrepo-com.svg",  },
    { name: "Frontend Mentor", userID: "Zy8712", link: "https://www.frontendmentor.io/profile/Zy8712", icon: "/icons/social-icons/coloured-icons/frontendmentor-brandfetch.jpeg", },
    { name: "LeetCode", userID: "Zy8712", link: "https://leetcode.com/Zy8712/", icon: "/icons/social-icons/coloured-icons/leetcode-brandfetch.jpeg",  },
    { name: "Sololearn", userID: "Bryan Li", link: "https://www.sololearn.com/en/profile/31735834", icon: "/icons/social-icons/coloured-icons/sololearn-icon.png", },
    { name: "Credly", userID: "bryan-li712", link: "https://www.credly.com/users/bryan-li712", icon: "/icons/social-icons/coloured-icons/credly-svgrepo-com.svg", },
    { name: "Holopin", userID: "@bryanli712", link: "https://www.holopin.io/@bryanli712#", icon: "/icons/social-icons/coloured-icons/holopin-logo.png",  },
    { name: "Medium", userID: "bryan-li712", link: "https://medium.com/@bryan-li712", icon: "/icons/social-icons/coloured-icons/medium-svgrepo-com.svg",  },
    { name: "CodeChef", userID: "Zy8712", link: "https://www.codechef.com/users/zy8712", icon: "/icons/social-icons/coloured-icons/codechef-brandfetch.jpeg",  },
    { name: "freeCodeCamp", userID: "bryan-li712", link: "https://www.freecodecamp.org/bryan-li712", icon: "/icons/social-icons/coloured-icons/freecodecamp-svgrepo-com.svg", },
    { name: "Duolingo", userID: "bryanli712", link: "https://www.duolingo.com/profile/bryanli712", icon: "/icons/social-icons/coloured-icons/duolingo-logo.svg", },
    { name: "Portfolio Site", userID: "bryanli.vercel.app", link: "https://bryanli.vercel.app/", icon: "/project-previews/personal-project-previews/portfolio-site/dragon-svgrepo-com.svg", },
    { name: "Certificate Site", userID: "", link: "", icon: "/project-previews/personal-project-previews/bryan-certificates-site/space-svgrepo-com.svg", },
    { name: "Project Site", userID: "", link: "", icon: "/icons/general-icons/difficulty-svgrepo-com.svg", },
];